### PR TITLE
Set attr_accessible to allow updating payment method settings

### PR DESCRIPTION
**Pull request by patrickmcelwee**
This was fixed on master with 2c12f396678149239dc8a4cba2bb8882876a842a, but not on the 1-0 branch.

### CODE REVIEW

**Comment by radar** [comment]
I've pull in your changes with @f1a9b1c, as well as @GeekOnCoffee's changes with @f6eb970. To my knowledge, this is all the mass-assignable stuff needed to fix this problem. Please try out the branch and let us know how it goes for you.

**Comment by patrickmcelwee** [comment]
Yep ... that seems to do it. I didn't realize the whole bug was due to mass assignment errors. Thanks!

**Comment by geermc4** [comment]
Was this removed from 1-3 ? I got this error on the lastest from 1-3 and looking at the code, the changes from f1a9b1cc28ad5cc2d3c993e77130a29fd4130ae5 are not in it https://github.com/spree/spree_paypal_express/blob/1-3-stable/app/models/spree/billing_integration/paypal_express.rb for example

**Comment by JDutil** [comment]
No attr_accessible is set for 1-3-stable in a base model https://github.com/spree/spree_paypal_express/blob/1-3-stable/app/models/spree/billing_integration/paypal_express_base.rb#L11 are you sure your using the latest commit in the 1-3-stable branch

**Comment by geermc4** [comment]
Yup, Gemfile.lock

``` ruby
GIT
  remote: git://github.com/spree/spree_paypal_express.git
  revision: b96c501bc4d6a675b1c0c8e8e49b6a64cd0b622c
  branch: 1-3-stable
  specs:
    spree_paypal_express (1.2.0)
      spree_core (~> 1.3.0)
```

**Comment by JDutil** [comment]
@geermc4 what is the particular attribute giving an error?  Could you provide the error/backtrace?

**Comment by geermc4** [comment]
Turned log level to debug but I saw nothing but sql. this is what I see on the confirmation page after comming back from paypal

Screen Shot 2013-03-25 at 11 58 54 AM

**Pull request closed without merging**
