### PR TITLE
Fixed the issue with missing 'payment' method in _order_details.html.erb.

### PR DESCRIPTION
**Pull request by pavelnikolov**
The issue was related to the fact that "payment" method has been replaced with "paymentS". So now there is a partial that visualizes each payment. I created exact match of this file and put there a <% elsif source.is_a? Spree::PaypalAccount %> check to put the paypal info if paypal payment is detected.

Related to issue #151

### CODE REVIEW

**Comment by radar** [comment]
This PR contains too many commits and does not apply cleanly to the 2-0-stable branch. Please rebase and update your fork so that this patch applies cleanly.

Thank you.

**Comment by pavelnikolov** [comment]
@radar  How do I do that? Sorry for the stupid question...

**Comment by radar** [comment]
First: there are no stupid questions or stupid people. You don't know and so you ask and then you learn. That is how learning happens. Stupidity is not asking in the first place, and that leads to ignorance. Asking is the _right_ thing to do.

---

Please cherry pick the commits out of this branch which are relevant to fixing this issue into a new branch:

``` bash
git cherry-pick <sha>
```

Once that's done, open a new PR with the new branch and I'll review.

Thanks!

**Comment by pavelnikolov** [comment]
@radar thank you for the explanation. I didn't know about the cherry-pick command. Now I will be prepared for the next bug-fix. Expect more commits from me soon!

**Comment by radar** [comment]
Thank you @pavelnikolov for persisting :)

**Pull request closed without merging**
