### PR TITLE
undefined class ActiveMerchant::Billing::PaypalExpressResponse

### LINKED ISSUE #32: undefined class ActiveMerchant::Billing::PaypalExpressResponse
Error when trying to access order/payments in admin:

undefined class/module ActiveMerchant::Billing::PaypalExpressResponse

To recreate, simply restart the spree site and try to view payment on a paypal express payment in the admin _without_ first doing an order checkout using paypal express.  The error disappears once you do a checkout in the store using paypal express.

This looks like a required class is not being loaded in the admin but is being loaded in the checkout process.

### PR DESCRIPTION
**Pull request by cnight**
added initializer to require appropriate ActiveMerchant files

[fixes #32]

### CODE REVIEW

**Comment by radar** [comment]
Beautiful, thanks! Added in @6ae311446800e72a05e8a9647e445fe46a7adbd0.

**Comment by cnight** [comment]
I don think this fix got merged

**Comment by radar** [comment]
Oops, it got merged, the push didn't go through though. How about now?

**Comment by cnight** [comment]
Looks good, thanks!

On Tue, Feb 14, 2012 at 10:30 PM, Ryan Bigg
reply@reply.github.com
wrote:

**Pull request closed without merging**
