### PR TITLE
Credit fix

### PR DESCRIPTION
**Pull request by cwise**
PayPal only accepts positive numbers for credits. As well, the currency is a required field. I've had both of these running in production for a while.

### CODE REVIEW

**Comment by cwise** [comment]
And man I hate how these pull requests put in too many commits - it's only 466eb09. Ignore the other commits (even  2a3c831 and 4366f3a which were from the wrong computer with the wrong code base).

**Comment by radar** [comment]
Done. Merged in @11c8935.

I would recommend committing each of your changes to a branch and then submitting a pull request for just that branch so that they only include the one commit.

**Comment by cwise** [comment]
Thanks. That's actually what I am doing Ryan - create a new topic branch, make the change, commit it and then use the GitHub interface for the pull request on that branch. No idea why it wants to send up every commit along the way. If there's a good guide, I'd love to see it (I've come across bunch of contradictory ones). I promise to do it correctly going forward.

**Comment by jumph4x** [comment]
@cwise We all make mistakes (some of us more often than others). 

So for people like that (me), there is git rebase-i | squash type deal. Read up on this trick here: http://book.git-scm.com/4_interactive_rebasing.html

**Comment by cwise** [comment]
Thanks kindly I'll definitely review that.

**Pull request closed without merging**
