### PR TITLE
Fixed Bug while retrieving Tax Adjustments

### PR DESCRIPTION
**Pull request by tvdeyen**

### CODE REVIEW

**Comment by tvdeyen** [comment]
And fixed another bug ;(

Rounding before converting to integer. Now all values are submitted correctly to paypal.

**Comment by jumph4x** [comment]
You have hardcoded 'EUR' currency codes, I doubt this will be accepted.

**Comment by jumph4x** [comment]
I see your corrections, appologize.

**Comment by LBRapid** [comment]
@BDQ Not sure what I should do with this. Those all look like valid fixes at the time, but with the tax refactor, etc, not sure how relevant this is anymore.

**Comment by BDQ** [comment]
Yeah it's pretty out of date, I'm going to close it.

@tvdeyen if you still think some of these changes are required (taking the tax refactor in core into consideration) then please rebase and resubmit.

**Comment by tvdeyen** [comment]
ok.

**Pull request closed without merging**
