### PR TITLE
fixes asset_url failing if logo is absolute url

### LINKED ISSUE #52: URI::InvalidComponentError in Spree::CheckoutController#paypal_payment
I have in my /config/initializers/mypreferences.rb file:

Spree::Config.set(:logo => 'https://s3.amazonaws.com/rkbb-prod/site/roots_logo.png')

When I follow the Paypal express button in the checkout I get the following error

```
URI::InvalidComponentError in Spree::CheckoutController#paypal_payment

bad component(expected absolute path component): https://s3.amazonaws.com/rkbb-prod/site/roots_logo.png
```

However, if I have a local file for the logo, eg:
Spree::Config.set(:logo => 'logo')
The error doesn't occur.

(note: I had to restart spree a few times, I'm not sure why but the config changes didn't always appear to be read. Even though I'd set a local file the the server was returning the previously set remote image)

### PR DESCRIPTION
**Pull request by steveroot**
Fixes https://github.com/spree/spree_paypal_express/issues/52

Tested by hand using:
Spree::Config.set(:logo => 'http://s3.amazonaws.com/rkbb-prod/site/roots_logo.png')
Spree::Config.set(:logo => 'rails.png')

Please check before pulling... it maybe simple to everyone else here, but I'm new to this ;-)

### CODE REVIEW

**Comment by radar** [comment]
This doesn't look right to me. Shouldn't the `header_image` key be inside the hash like it was before?

**Comment by steveroot** [comment]
I thought the same thing until I tried it.
I think IF statements can't be run inside a hash? At least, I couldn't find any examples by googling.
So, after the rest of the hash is created as before, the if statement inserts the appropriate `header_image` into the hash at the end.
I'd be happy to be told there's a neater way of doing it and I'll work on a new version.

**Comment by radar** [comment]
Do the `if` statement before the hash, define a local variable inside the `if` and then use that in the complete hash. Right now you are building that first big hash and then completely disregarding it, only returning the logo information. This is broken.

**Comment by steveroot** [comment]
Thanks for the help Radar, all reworked at:
https://github.com/steveroot/spree_paypal_express/commit/1a59c10d192fa255e9c512a3f6f341bed2ea2980
.. I can't see how to update this pull request, so I'll start a new one.

**Pull request closed without merging**
