### PR TITLE
Allows checkout from cart

### PR DESCRIPTION
**Pull request by v-fedorov**
Paypal now does not look for address fields before redirecting unless specified otherwise in payment options

### CODE REVIEW

**Comment by jumph4x** [comment]
Interesting. Is there any way for us to build specs for the instant update shipping quote feature?

**Comment by v-fedorov** [comment]
the request was premature, working on instant update right now. will update the request when finished. as of now no shipping costs are calculated

**Comment by jumph4x** [comment]
@v-fedorov Excellent!

**Comment by Dharshi** [comment]
Hi 
I am trying to allow checkout from cart page. I am using the latest spree_paypal_express and with spree latest version. As document says I have checked the checkout from cart in admin module. But I am not seeing a paypal checkout button in my cart page. 

Could you help please help  me to figure out what I am doing wrong here ?

**Comment by JDutil** [comment]
Currently there is no override that adds a button to the cart page.  You'll need to add one to your application or add one to the extension.

**Comment by Dharshi** [comment]
Thanks for the information. I will add an override to my application

**Pull request closed without merging**
